steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/c3solver', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/c3solver']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'c3solver',
        '--image',
        'gcr.io/$PROJECT_ID/c3solver',
        '--region',
        'us-central1',
        '--platform',
        'managed',
      ]
images:
  - gcr.io/$PROJECT_ID/c3solver
